# Generated by Django 4.2.7 on 2023-12-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(default='../media/images/default_profile_photo.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='university_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
