# Generated by Django 4.2.7 on 2023-12-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_account_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
