# Generated by Django 4.2.7 on 2023-12-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityStudents',
            fields=[
                ('university_id', models.IntegerField(primary_key=True, serialize=False)),
                ('number_of_hours', models.IntegerField()),
            ],
        ),
    ]
