# Generated by Django 4.2.7 on 2023-12-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_universitystudents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniversityStudents',
            new_name='University_students',
        ),
    ]
