# Generated by Django 4.2.7 on 2023-12-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_universitystudents_university_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_students',
            name='application_subject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university_students',
            name='graduation1_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university_students',
            name='junior_project',
            field=models.BooleanField(default=False),
        ),
    ]
