# Generated by Django 4.2.7 on 2023-12-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_university_students_application_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_students',
            name='GPA',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university_students',
            name='first_name',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university_students',
            name='last_name',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
