# Generated by Django 4.2.7 on 2023-11-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_requests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
